#!/bin/bash

msg=`cat $1`

if [[ $msg = feat* ]]; then
  msg="🌟 ${msg}"
elif [[ $msg = fix* ]]; then
  msg="🛠 ${msg}"
elif [[ $msg = build* ]]; then
  msg="📦 ${msg}"
elif [[ $msg = perf* ]]; then
  msg="⚡ ${msg}"
elif [[ $msg = refactor* ]]; then
  msg="🚧 ${msg}"
elif [[ $msg = style* ]]; then
  msg="💄 ${msg}"
elif [[ $msg = docs* ]]; then
  msg="📖 ${msg}"
elif [[ $msg = test* ]]; then
  msg="✅ ${msg}"
elif [[ $msg = ci* ]]; then
  msg="🤖 ${msg}"
elif [[ $msg = revert* ]]; then
  msg="⏳ ${msg}"
fi

echo "$msg" > $1
